export const ADD_TODO = "ADD_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const ADD_TO_WORKINPROGRESS = "ADD_TO_WORKINPROGRESS";
export const DELETE_FROM_WORKINPROGRESS = "DELETE_FROM_WORKINPROGRESS";
export const ADD_TO_COMPLETE = "ADD_TO_COMPLETE";
